# TODO: Consider describing each field and adding example with all full config.
# It will make more comfortable to use the crate.

host = "0.0.0.0"
port = 8000

[log]
level = "info"
# enabled = true              # Whether you want to store log in log files.
# TODO: Should probably have extra parameters. Log to file?

[trace]
level = "info"
# enabled = true              # Whether tracing/telemetry is enabled.
# TODO: Should probably have extra parameters.

[service]
name = "Rust"

[private]

[application]
name = "platform"
version = "0.1"

# TODO: This name has dot. Might be problem to get form environment variable.
[server.tls]
key_path = "/tls.key"
cert_path = "/tls.cert"

[private]
key = "xxx"

[aws]
...
...
...
